spring:
  server:
    error:
    include-message: always
    include-binding-errors: always
  datasource:
    url: jdbc:mysql://office.nasbg.com:33062/bootcamp_java_23_august_team2
    username: bootcamp_java_23_august_team2
    password: 3L3G%OW8#EgcEx_sa(86
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: mail.nasbg.com
    port: 465
    username: "bootcamp@nasbg.com"
    password: '%61%,g]AI,g_'
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

paypal.mode: sandbox
paypal.client.id: "AZ5qsPJOXTN0b7BtoXK8ZvXaZL5pGWygKH8UG3ANIpfRtR0ozZ2RZECtB4cU7P9QMoN2VztoUJCZMpP4"
paypal.client.secret: "EGcYuLhgRsgUyVpkeJ5-ueiOuc4dLMt4VlcaRA7-qMiMm4bTqVvGnyCnIir526wa-sAFNW1NPsWvy1bC"

              # For testing purposes
#    url: jdbc:mysql://localhost:3306/moonlight_hotel_test?createDatabaseIfNotExist=true
#    username: root
#    password: root
