spring:
  server:
    error:
    include-message: always
    include-binding-errors: always
  datasource:
#    url: jdbc:mysql://office.nasbg.com:33062/bootcamp_java_23_august_team2
#    username: bootcamp_java_23_august_team2
#    password: 3L3G%OW8#EgcEx_sa(86
    url: jdbc:mysql://localhost:3306/hotel_moonlight?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
